### PR TITLE
gnu(9920)=12142

### PR DESCRIPTION
**Pull request by markuspf**
This took `25219.574` seconds to construct the groups, yielding one pair of groups that grpconst could not split. The non-isomorphism test took long, but I do not have a record of the time, so it would be good if we got that with verification.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you for submitting new gnu(n). We will recalculate it and add to the database if we get the same result.

Checklist for the reviewer:
- [x] checked and assigned labels "new (n<50000)" or "recomputation", if needed
- [x] indicated that the recomputation has been started
- [x] reproducible value of gnu(n)
- [x] no essential runtime differences
- [x] sufficient level of technical details
- [x] assigned label "replicated" after successful review

Checklist for the maintainer:
- [x] correct arguments of commands to store data
- [x] correct location of new line in the data file
- [x] mention reviewer in the commit message

**Comment by olexandr-konovalov** [comment]
I have restarted the replication, but I already see that the value in the commit message and the description of the PR differs from the value in the code.

**Comment by olexandr-konovalov** [comment]
gnu(9920)=12142

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 13242896 ms
Returned a list of length 12141 containing 12140 groups and 1 sublists
Length of sublists : [ 2 ]
Runtime to check non-isomorphism of groups in pairs: 198279596

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS3 v2 instance (4 cores, 14 GB RAM)

**Comment by olexandr-konovalov** [comment]
@markuspf perhaps you just entered the length of the constructed list ? If you edit the PR title and amend commit text, I will merge this.

**Comment by markuspf** [comment]
I seem to have a strong Copy&Paste impediment. I think next I should find a way to automatically submit these results as a pull request.

**Comment by olexandr-konovalov** [comment]
The same result was also reported by me in #35.

**Pull request merged**
