### PR TITLE
gnu(9072)=24770

### PR DESCRIPTION
**Pull request by markuspf**
This took `18132.715` seconds to compute.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you for submitting new gnu(n). We will recalculate it and add to the database if we get the same result.

Checklist for the reviewer:
- [x] checked and assigned labels "new (n<50000)" or "recomputation", if needed
- [x] indicated that the recomputation has been started
- [ ] reproducible value of gnu(n)
- [ ] no essential runtime differences
- [ ] sufficient level of technical details
- [ ] assigned label "validated" after successful review

Checklist for the maintainer:
- [ ] correct arguments of commands to store data
- [x] correct location of new line in the data file
- [x] mention reviewer in the commit message

**Comment by olexandr-konovalov** [comment]
I must be running this already quite for a while and it it still there:

```
****************************************
Constructed a list of length 24767
It contains 24764 groups and 3 sublists
Length of sublists are [ 2, 2, 2 ]
```

This was started in GAP 4.8.3, before the recent release of GAP 4.8.4 (even the output is like in the old version of the script. I will try to check this with other GAP versions.

**Comment by olexandr-konovalov** [comment]
gnu(9072)=24770

GAP      4.8.4
GrpConst 2.5
Runtime of ConstructAllGroups: 8992513 ms (2.5 hrs)
Returned a list of length 24767 containing 24764 groups and 3 sublists
Length of sublists : [ 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 15601567 ms (4.33 hrs)

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

To maintainers: for new results, add to data/gnudata.g this line:
GNU_SAVE( 9072, 24770, WITH_GC );

**Comment by olexandr-konovalov** [comment]
I've interrupted the long-running calculation in GAP 4.8.3 to see where the non-isomorphism check was, and found

```


^CError, user interrupt in
  m := m * mm; at /home/alexk/scratch/gap4r8p3/lib/wordlett.gi:707 called from 
MappedWord( i[5], free{[ tlev .. len ]}, imgs ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:880 called from
func( elm ) at /home/alexk/scratch/gap4r8p3/lib/coll.gi:1610 called from
ForAll( sortrels[tlev], function ( i )
      return i[2] = Order( MappedWord( i[5], free{[ tlev .. len ]}, imgs ) );
  end ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:880 called from
TestRels( i ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:960 called from
MorClassLoop( H, combi, result, 7 ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:1346 called from
...  at line 1 of *stdin*
you can 'return;'
brk> m;
f1^2*f6^2*f7^4*f8*f9^2
brk> mm; 
f1*f2*f4*f5*f6^2
brk> Where(100000);
MappedWord( i[5], free{[ tlev .. len ]}, imgs ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:880 called from
func( elm ) at /home/alexk/scratch/gap4r8p3/lib/coll.gi:1610 called from
ForAll( sortrels[tlev], function ( i )
      return i[2] = Order( MappedWord( i[5], free{[ tlev .. len ]}, imgs ) );
  end ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:880 called from
TestRels( i ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:960 called from
MorClassLoop( H, combi, result, 7 ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:1346 called from
Morphium( G, H, false ) at /home/alexk/scratch/gap4r8p3/lib/morpheus.gi:1994 called from
IsomorphismGroups( x[1], x[2] ) at lib/grpconst.g:38 called from
func( C[i] ) at /home/alexk/scratch/gap4r8p3/lib/coll.gi:743 called from
List( sublists, function ( x )
      return IsomorphismGroups( x[1], x[2] );
  end ) at lib/grpconst.g:38 called from
<function "GnuByConstructAllGroups">( <arguments> )
 called from read-eval loop at line 3 of *errin*
brk> 
```

I have restarted it with GAP 4.8.3 again to see what happens.

**Comment by olexandr-konovalov** [comment]
This is the report from GAP 4.8.3 restarted yesterday:

```
Constructed a list of length 24767
It contains 24764 groups and 3 sublists
Length of sublists are [ 2, 2, 2 ]

24767<=gnu(9072)<=24770

Runtime of this construction: 14236401 ms (3.95 hrs)
Now checking non-isomorphism of groups in sublists ...
Success! All pairs contain non-isomorphic groups

gnu(9072)=24770

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 14236401 ms (3.95 hrs)
Returned a list of length 24767 containing 24764 groups and 3 sublists
Length of sublists : [ 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 10347253 ms (2.87 hrs)

To maintainers: for new results, add to data/gnudata.g this line:
GNU_SAVE( 9072, 24770, WITH_GC );
```

but obviously the previous attempt of doing this in GAP 4.8.3 was running for one month!

**Comment by olexandr-konovalov** [comment]
Another run on the same machine with GAP 4.8.3:

```
gnu(9072)=24770

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 14270135 ms (3.96 hrs)
Returned a list of length 24767 containing 24764 groups and 3 sublists
Length of sublists : [ 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 10377828 ms (2.88 hrs)
```

I think this is reproducible and will merge it now.

**Comment by olexandr-konovalov** [comment]
The initial PR by @markuspf does not include details about sublists, so I have rerun this one more time with master branch. Same result, and three pairs of groups to split, with the runtime to construct 14338657 ms (3.98 hrs) and to split 22191117 ms (6.16 hrs).

**Comment by alex-konovalov** [comment]
This is closed via commit https://github.com/alex-konovalov/gnu/commit/88c91c7c018e1c174595007302d03ef9fa997c7e

**Pull request merged**
