### PR TITLE
gnu(5040)=4539, gnu(5280)=7564, gnu(6240)=9304, gnu(7920)=4186 

### PR DESCRIPTION
**Pull request by markuspf**
Please check that you provide the following details when submitting new values of Gnu(n):
- [x] Version of GAP and critical packages: GrpConst, Cubefree, etc.
- [x] Brief description of the computer used for the calculation (operating system, processor, RAM)
- [x] Runtime required for the calculation
- [x] GAP commands used for the calculation
- [x] Confirm that the output `r` of `ConstructAllGroups` is a _list_ of groups (`ForAll(r,IsGroup)` should return `true`), otherwise confirm that if the output contained lists of groups, then those groups were also shown to be pairwise non-isomorphic.

This is an attempt at bulk-submission for gnu, all lists were obtained using `grpconst.g` 

GAP: `e403849e47a7bdf008c9406a15912559fe2e9f8c`
GrpConst: 2.5

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you for submitting new gnu(n). We will recalculate it and add to the database if we get the same result.

Checklist for the reviewer:
- [x] checked and assigned labels "new (n<50000)" or "recomputation", if needed
- [x] set "replication needed" label (unless it starts immediately)
- [x] changed it to "replication in progress" label when the replication has been started
- [ ] changed it to "replicated" after successful replication review 
- [ ] reproducible value of gnu(n)
- [ ] no essential runtime differences
- [ ] sufficient level of technical details

Checklist for the maintainer:
- [ ] correct arguments of commands to store data
- [ ] correct location of new line in the data file
- [ ] mention reviewer in the commit message

Orders included:
- [x] gnu(5040)=4539
- [x] gnu(5280)=7564
- [x] gnu(6240)=9304
- [x] gnu(6720)=106765
- [x] gnu(7920)=4186

**Comment by olexandr-konovalov** [comment]
@markuspf as README.md says, for bulk submissions each the commit message should look like the summary produced by GnuByConstructAllGroups - one should be able to find out versions used for the calculation just looking at the commit, without the necessity to trace the history of the whole PR.

**Comment by markuspf** [comment]
As I said earlier the output is lost in logging messages, which is why I'd like to write all relevant information to a file anyway.

I also added `6720` to this PR now becasuse the splitting of the 4 lists didn't take that long.

**Comment by olexandr-konovalov** [comment]
Ok - since #6720 is already in replication, hopefully it will not take too much time to wait. I've created #108 with TODOs to improve usability of `lib.grpconst.g`.

**Comment by olexandr-konovalov** [comment]
gnu(7920)=4186

GAP      4.8.3
GrpConst 2.5
Runtime: 7867798 ms (2.19 hrs)
Isomorphic groups eliminated

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
gnu(6240)=9304

GAP      4.8.3
GrpConst 2.5
Runtime: 6447438 ms (1.79 hrs)
Isomorphic groups eliminated

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
gnu(5280)=7564

GAP      4.8.3
GrpConst 2.5
Runtime: 4342785 ms (1.21 hrs)
Isomorphic groups eliminated

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
gnu(5040)=4539

GAP      4.8.3
GrpConst 2.5
Runtime: 2296560 ms (38.27 min)
Isomorphic groups eliminated

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
@markuspf all looks good, it remains to wait until the end of the replication of gnu(6720).

**Comment by olexandr-konovalov** [comment]
gnu(6720)=106765

GAP      4.8.3
GrpConst 2.5
Runtime: 96667897 ms (1.12 days)
Isomorphic groups eliminated

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
@markuspf with GAP 4.8.3, no lists to split for gnu(6720) at all.

**Comment by olexandr-konovalov** [comment]
@markuspf if you would take out gnu(6720) from this PR (because it is duplicated in #99 and I'd like to look more at it because GAP 4.8.3 does not return sublists, but master does), I would be happy to merge the other four orders.

**Comment by markuspf** [comment]
@alex-konovalov done (and rebased)

**Pull request merged**
