### PR TITLE
gnu(9152)=10723

### PR DESCRIPTION
**Pull request by markuspf**
This took `17768.745` seconds to construct the groups.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you for submitting new gnu(n). We will recalculate it and add to the database if we get the same result.

Checklist for the reviewer:
- [x] checked and assigned labels "new (n<50000)" or "recomputation", if needed
- [x] indicated that the recomputation has been started
- [ ] reproducible value of gnu(n)
- [ ] no essential runtime differences
- [ ] sufficient level of technical details
- [ ] assigned label "validated" after successful review

Checklist for the maintainer:
- [ ] correct arguments of commands to store data
- [ ] correct location of new line in the data file
- [ ] mention reviewer in the commit message

**Comment by olexandr-konovalov** [comment]
gnu(9152)=10723

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 9851608 ms
Returned a list of length 10720 containing 10717 groups and 3 sublists
Length of sublists : [ 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 37398396

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Comment by olexandr-konovalov** [comment]
@markuspf you did not mention that sublists were returned. Were they, or this is the case when the master branch performed better?

**Comment by markuspf** [comment]
I didn't print that information when I did the computation. Since it won't take too long to redo I can just run it again.

**Comment by olexandr-konovalov** [comment]
This is superseded by #93 which includes details about sublists returned by the output of `ConstructAllGroups`.

**Pull request closed without merging**
