### PR TITLE
gnu(3136)=8085

### PR DESCRIPTION
**Pull request by markuspf**
GAP      e403849e47a7bdf008c9406a15912559fe2e9f8c
GrpConst 2.5
Runtime of ConstructAllGroups: 3494984 ms
Returned a list of length 8081 containing  8077 groups and 4 sublists
Length of sublists : [ 2, 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 14573440

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Thank you for submitting new gnu(n). We will recalculate it and add to the database if we get the same result.

Checklist for the reviewer:
- [x] checked and assigned labels "new (n<50000)" or "recomputation", if needed
- [x] set "replication needed" label (unless it starts immediately)
- [x] changed it to "replication in progress" label when the replication has been started
- [x] changed it to "replicated" after successful replication review 
- [x] reproducible value of gnu(n)
- [x] no essential runtime differences
- [x] sufficient level of technical details

Checklist for the maintainer:
- [x] correct arguments of commands to store data
- [ ] correct location of new line in the data file
- [x] mention reviewer in the commit message

**Comment by gnufinder** [comment]
I submitted this gnu because I did not know that it was already done.

**Comment by gnufinder** [comment]
I accidently pulled a request here. How can I undo this ?

**Comment by gnufinder** [comment]
I recalculated the gnu because I thought the status would be open. The calculation perfectly approves the posted result.

**Comment by gnufinder** [comment]
Should I undo the accidentical reference. If yes, how can I do that ?

**Comment by olexandr-konovalov** [comment]
gnu(3136)=8085

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 2342512 ms (39.03 min)
Returned a list of length 8081 containing 8077 groups and 4 sublists
Length of sublists : [ 2, 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 91906223 ms (1.06 days)

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

**Pull request merged**
